import type { FullInvestigationDataset, SahyogPackage } from '../types/api';

export const SAMPLE_CASE_ID = 'case-tron-usdt-9942';
export const SAMPLE_TARGET_WALLET = 'TGCCfE3KJiXA2LNiKCmLZ6DT6NdL1zDWPY';

export const MOCK_INVESTIGATION_DATASET: FullInvestigationDataset = {
  summary: {
    case_id: SAMPLE_CASE_ID,
    job_id: 'job-inv-883192',
    target_wallet: SAMPLE_TARGET_WALLET,
    chain: 'TRON',
    asset: 'USDT',
    investigation_status: 'COMPLETED',
    execution_duration_seconds: 0.28,
    completed_at: new Date().toISOString(),
    total_wallets_traced: 3,
    total_transactions_analyzed: 2,
    total_paths_found: 1,
    risk_score: 85.0,
    raw_risk_score: 85.0,
    contextual_risk_score: 85.0,
    risk_level: 'HIGH',
    service_entity_context: false,
    primary_vasp_name: 'Bybit',
    primary_vasp_confidence: 100.0,
    evidence_count: 4,
  },
  risk_indicator: {
    trace_id: 'tr-mock-9942',
    case_id: SAMPLE_CASE_ID,
    starting_wallet: SAMPLE_TARGET_WALLET,
    chain: 'TRON',
    asset: 'USDT',
    risk_score: 85.0,
    raw_risk_score: 85.0,
    contextual_risk_score: 85.0,
    contextual_interpretation: 'SUSPICIOUS_HIGH_VELOCITY_FLOW_TO_VASP',
    risk_level: 'HIGH',
    component_contributions: {
      high_velocity_movement: 45.0,
      peel_chain_typology: 25.0,
      value_retention: 15.0,
    },
    contributing_factors: [
      'Rapid successive multi-hop transfers detected (Δt = 45s)',
      'High value retention across multi-hop chain (99.5% retention)',
      'Fund flow terminates at verified VASP deposit sweep endpoint (Bybit)',
    ],
    is_known_service_entity: false,
    service_entity_context: false,
    false_positive_mitigations: [],
    analyzed_at: new Date().toISOString(),
  },
  vasp_attribution: {
    trace_id: 'tr-mock-9942',
    case_id: SAMPLE_CASE_ID,
    starting_wallet: SAMPLE_TARGET_WALLET,
    chain: 'TRON',
    asset: 'USDT',
    resolution_status: 'RESOLVED',
    summary_statement: 'Fund flow terminates at known VASP deposit endpoint Bybit with 100% attribution confidence.',
    has_high_confidence_match: true,
    candidates: [
      {
        candidate_name: 'Bybit',
        endpoint_address: 'TBpr1tQ5kvoKMv85XsCESVavYo4oZZdWpY',
        entity_role: 'EXCHANGE_HOT_WALLET',
        attribution_type: 'TERMINAL_ENDPOINT',
        confidence_band: 'HIGH',
        attribution_confidence: 100.0,
        source_confidence: 100.0,
        endpoint_hop_distance: 2,
        deposit_tx_count: 16,
        value_transferred: 9950.0,
        value_retention_percent: 99.5,
        matched_relevance_reasons: [
          'Direct matching against Specter VASP Intelligence Database',
          'High value retention across 2 downstream hops (99.5%)',
          'Terminal deposit sweep at verified Bybit infrastructure',
        ],
        why_this_vasp: [
          'Terminal endpoint matches verified Bybit infrastructure in Specter Intelligence Database',
          'High value retention (99.5%) across 2 downstream hops',
          'Direct path convergence from suspicious wallet TGCCfE3KJiXA2LNiKCmLZ6DT6NdL1zDWPY to verified Bybit endpoint',
        ],
        evidence_summary: 'On-chain transaction transfers $9,950 USDT directly to verified Bybit sweep endpoint TBpr1tQ5kvoKMv85XsCESVavYo4oZZdWpY.',
      },
    ],
  },
  findings: [
    {
      finding_id: 'fnd-risk-001',
      case_id: SAMPLE_CASE_ID,
      job_id: 'job-inv-883192',
      finding_type: 'TRANSACTION_FLOW_RISK',
      title: 'Transaction-Flow Risk Indicator: MODERATE (35.0/100)',
      description: 'Composite risk indicator for target wallet TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t. Unmitigated raw structural score: 78.0/100. Service Entity Context: True. Contextual score: 35.0/100.',
      severity: 'MODERATE',
      confidence: 0.9,
      supporting_evidence_ids: ['ev-risk-001'],
    },
    {
      finding_id: 'fnd-vel-001',
      case_id: SAMPLE_CASE_ID,
      job_id: 'job-inv-883192',
      finding_type: 'HIGH_VELOCITY_MOVEMENT',
      title: 'Rapid Successive Fund Movement (HIGH Severity)',
      description: 'Rapid successive fund transfer chain detected: 3 transfers across 3 hops total $29,780.00 USDT in 41.2 seconds. Minimum Δt: 12.4s. Average Δt: 20.6s.',
      severity: 'HIGH',
      confidence: 0.92,
      supporting_evidence_ids: ['ev-vel-001'],
    },
    {
      finding_id: 'fnd-typ-001',
      case_id: SAMPLE_CASE_ID,
      job_id: 'job-inv-883192',
      finding_type: 'RAPID_PEEL_LIKE_MOVEMENT',
      title: 'Transaction Typology Pattern: Rapid Peel Like Movement',
      description: 'Peel-like structural movement: sequential fund splits over 3 hops with 97.8% value retention.',
      severity: 'HIGH',
      confidence: 0.88,
      supporting_evidence_ids: ['ev-typ-001'],
    },
    {
      finding_id: 'fnd-vasp-001',
      case_id: SAMPLE_CASE_ID,
      job_id: 'job-inv-883192',
      finding_type: 'VASP_ATTRIBUTION',
      title: 'VASP Endpoint Attribution: Binance Hot Wallet',
      description: 'Fund flow terminates at known VASP entity Binance Hot Wallet (KNOWN_DEPOSIT_ENDPOINT). Matched endpoint address: TJCnKsPa7y5okkXvQWBzxaZ2MJK7JBFZ12.',
      severity: 'INFO',
      confidence: 0.95,
      supporting_evidence_ids: ['ev-vasp-001'],
    },
  ],
  evidence: [
    {
      evidence_id: 'ev-risk-001',
      finding_id: 'fnd-risk-001',
      case_id: SAMPLE_CASE_ID,
      evidence_type: 'DERIVED_ANALYSIS',
      finding: 'Transaction-Flow Risk Indicator assessed at 35.0/100 (MODERATE). Raw structural score: 78.0/100.',
      supporting_tx_hashes: [],
      supporting_addresses: [SAMPLE_TARGET_WALLET],
      supporting_path_ids: ['path-tron-001'],
      source_id: 'SRC_SPECTER_RISK_ENGINE',
      source_name: 'Specter Risk Intelligence Engine v1.0',
      explorer_urls: [`https://tronscan.org/#/address/${SAMPLE_TARGET_WALLET}`],
      confidence: 0.9,
      scoring_factors: { raw_risk_score: 78.0, contextual_risk_score: 35.0 },
      retrieval_timestamp: new Date().toISOString(),
    },
    {
      evidence_id: 'ev-vel-001',
      finding_id: 'fnd-vel-001',
      case_id: SAMPLE_CASE_ID,
      evidence_type: 'ON_CHAIN',
      finding: 'High-velocity movement alert: 3 successive transfers within 41.2 seconds.',
      supporting_tx_hashes: ['tx-tron-001', 'tx-tron-002', 'tx-tron-003'],
      supporting_addresses: [SAMPLE_TARGET_WALLET, 'THopWallet11111111111111111', 'THopWallet22222222222222222', 'TJCnKsPa7y5okkXvQWBzxaZ2MJK7JBFZ12'],
      supporting_path_ids: ['path-tron-001'],
      source_id: 'SRC_SPECTER_VELOCITY_ENGINE',
      source_name: 'Specter High-Velocity Movement Engine v1.0',
      explorer_urls: [
        'https://tronscan.org/#/transaction/tx-tron-001',
        'https://tronscan.org/#/transaction/tx-tron-002',
        'https://tronscan.org/#/transaction/tx-tron-003',
      ],
      confidence: 0.92,
      scoring_factors: { velocity_score: 84.0, transfer_count: 3, minimum_delta_t: 12.4 },
      retrieval_timestamp: new Date().toISOString(),
    },
    {
      evidence_id: 'ev-typ-001',
      finding_id: 'fnd-typ-001',
      case_id: SAMPLE_CASE_ID,
      evidence_type: 'DERIVED_ANALYSIS',
      finding: 'Detected structural transaction typology: RAPID_PEEL_LIKE_MOVEMENT with 97.8% value retention.',
      supporting_tx_hashes: ['tx-tron-001', 'tx-tron-002', 'tx-tron-003'],
      supporting_addresses: ['THopWallet11111111111111111', 'THopWallet22222222222222222'],
      supporting_path_ids: ['path-tron-001'],
      source_id: 'SRC_SPECTER_TYPOLOGY_ENGINE',
      source_name: 'Specter Transaction Typology Engine v1.0',
      explorer_urls: ['https://tronscan.org/#/transaction/tx-tron-001'],
      confidence: 0.88,
      scoring_factors: { value_retention: 97.8, hop_count: 3 },
      retrieval_timestamp: new Date().toISOString(),
    },
    {
      evidence_id: 'ev-vasp-001',
      finding_id: 'fnd-vasp-001',
      case_id: SAMPLE_CASE_ID,
      evidence_type: 'ENTITY_INTELLIGENCE',
      finding: 'VASP Attribution candidate resolved: Bybit (TERMINAL_ENDPOINT) confidence 100/100.',
      supporting_tx_hashes: ['tx-tron-002'],
      supporting_addresses: ['TBpr1tQ5kvoKMv85XsCESVavYo4oZZdWpY'],
      supporting_path_ids: ['path-tron-001'],
      source_id: 'SRC_SPECTER_VASP_DB',
      source_name: 'Specter VASP Intelligence Database',
      explorer_urls: ['https://tronscan.org/#/address/TBpr1tQ5kvoKMv85XsCESVavYo4oZZdWpY'],
      confidence: 1.0,
      scoring_factors: { attribution_confidence: 100.0, source_confidence: 100.0 },
      retrieval_timestamp: new Date().toISOString(),
    },
  ],
  velocity_analysis: {
    trace_id: 'tr-mock-9942',
    case_id: SAMPLE_CASE_ID,
    starting_wallet: SAMPLE_TARGET_WALLET,
    chain: 'TRON',
    asset: 'USDT',
    has_high_velocity_pattern: true,
    status: 'RESOLVED_ALERT',
    summary: 'High-velocity transfer pattern identified across 3 successive hops.',
    alerts: [
      {
        alert_id: 'alert-vel-001',
        trace_id: 'tr-mock-9942',
        case_id: SAMPLE_CASE_ID,
        alert_type: 'HIGH_VELOCITY_MOVEMENT',
        severity: 'HIGH',
        velocity_score: 84.0,
        transfer_count: 3,
        total_amount: 29780.0,
        duration_seconds: 41.2,
        minimum_delta_t: 12.4,
        average_delta_t: 20.6,
        maximum_delta_t: 28.8,
        unique_recipients: 3,
        downstream_hops: 3,
        supporting_transactions: ['tx-tron-001', 'tx-tron-002', 'tx-tron-003'],
        supporting_wallets: [SAMPLE_TARGET_WALLET, 'THopWallet11111111111111111', 'THopWallet22222222222222222', 'TJCnKsPa7y5okkXvQWBzxaZ2MJK7JBFZ12'],
        reason_codes: ['RAPID_SUCCESSIVE_TRANSFERS', 'HIGH_VALUE_RETENTION_RAPID_CHAIN'],
        score_components: { temporal_velocity: 45.0, value_density: 25.0, hop_acceleration: 14.0 },
        explanation: '3 transfers totaling $29,780 USDT completed in 41.2 seconds with 12.4s minimum interval.',
        analyzed_at: new Date().toISOString(),
      },
    ],
    metrics: { total_volume: 29780.0, transfer_count: 3 },
  },
  typology_analysis: {
    trace_id: 'tr-mock-9942',
    case_id: SAMPLE_CASE_ID,
    starting_wallet: SAMPLE_TARGET_WALLET,
    chain: 'TRON',
    asset: 'USDT',
    status: 'TYPOLOGIES_DETECTED',
    summary: 'Structural peel-like transaction movement detected.',
    typologies: [
      {
        typology_id: 'typ-001',
        typology_name: 'RAPID_PEEL_LIKE_MOVEMENT',
        severity: 'HIGH',
        description: 'Sequential fund transfer chain with continuous value retention above 95% and short time delta.',
        trigger_conditions: ['HOPS_GE_2', 'VALUE_RETENTION_GE_90', 'AVG_DELTA_T_LE_60s'],
        metrics: { hop_count: 3, value_retention_percent: 97.8, average_delta_t_seconds: 20.6 },
        supporting_transactions: ['tx-tron-001', 'tx-tron-002', 'tx-tron-003'],
        supporting_wallets: [SAMPLE_TARGET_WALLET, 'THopWallet11111111111111111', 'THopWallet22222222222222222', 'TJCnKsPa7y5okkXvQWBzxaZ2MJK7JBFZ12'],
        supporting_paths: ['path-tron-001'],
        confidence: 0.88,
        is_known_service: true,
      },
    ],
    analyzed_at: new Date().toISOString(),
  },
  trace_result: {
    trace_id: 'tr-mock-9942',
    case_id: SAMPLE_CASE_ID,
    starting_wallet: SAMPLE_TARGET_WALLET,
    chain: 'TRON',
    asset: 'USDT',
    status: 'COMPLETED',
    truncated: false,
    total_wallets_discovered: 3,
    total_transactions_analyzed: 2,
    total_edges_discovered: 2,
    total_paths_found: 1,
    processing_time_seconds: 0.28,
    started_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
    paths: [
      {
        path_id: 'path-tron-001',
        wallet_sequence: [
          SAMPLE_TARGET_WALLET,
          'THopWallet11111111111111111',
          'TBpr1tQ5kvoKMv85XsCESVavYo4oZZdWpY',
        ],
        hop_count: 2,
        initial_amount: 10000.0,
        final_amount: 9950.0,
        value_retention_percent: 99.5,
        elapsed_time_seconds: 45.0,
        relevance_score: 98.5,
        relevance_explanation: [
          'High value retention across 2 downstream hops (99.5%)',
          'Direct rapid transfer chain (45.0s elapsed)',
          'Path terminates at verified Bybit deposit endpoint',
        ],
        cycle_detected: false,
        metrics: {},
        hops: [
          {
            hop_number: 1,
            from_address: SAMPLE_TARGET_WALLET,
            to_address: 'THopWallet11111111111111111',
            tx_hash: 'tx-tron-001',
            asset: 'USDT',
            amount: 10000.0,
            timestamp: new Date(Date.now() - 45000).toISOString(),
            delta_t_seconds: 0.0,
            explorer_url: 'https://tronscan.org/#/transaction/tx-tron-001',
          },
          {
            hop_number: 2,
            from_address: 'THopWallet11111111111111111',
            to_address: 'TBpr1tQ5kvoKMv85XsCESVavYo4oZZdWpY',
            tx_hash: 'tx-tron-002',
            asset: 'USDT',
            amount: 9950.0,
            timestamp: new Date().toISOString(),
            delta_t_seconds: 45.0,
            explorer_url: 'https://tronscan.org/#/transaction/tx-tron-002',
          },
        ],
      },
    ],
  },
};

export const MOCK_SAHYOG_PACKAGE: SahyogPackage = {
  sahyog_metadata: {
    integration_status: 'READY FOR AUTHORISED API INTEGRATION',
    generator_engine: 'Specter High-Velocity Blockchain Intelligence Platform v1.0',
    export_timestamp: new Date().toISOString(),
    schema_version: 'SAHYOG_READY_V1',
    notice: 'CONFIDENTIAL LAW ENFORCEMENT INVESTIGATION PACKAGE - AUTHORISED USE ONLY',
  },
  case_details: {
    case_id: SAMPLE_CASE_ID,
    job_id: 'job-inv-883192',
    target_wallet: SAMPLE_TARGET_WALLET,
    chain: 'TRON',
    asset: 'USDT',
    investigation_status: 'COMPLETED',
    execution_duration_seconds: 0.28,
    completed_at: new Date().toISOString(),
  },
  risk_assessment: MOCK_INVESTIGATION_DATASET.risk_indicator,
  vasp_attribution: MOCK_INVESTIGATION_DATASET.vasp_attribution,
  analytical_findings: MOCK_INVESTIGATION_DATASET.findings,
  evidence_ledger: MOCK_INVESTIGATION_DATASET.evidence,
  velocity_analysis: MOCK_INVESTIGATION_DATASET.velocity_analysis,
  typology_analysis: MOCK_INVESTIGATION_DATASET.typology_analysis,
  fund_tracing_graph: MOCK_INVESTIGATION_DATASET.trace_result,
};